# -*- coding: utf-8 -*-
"""Topic_classification_AI_Model_.ipynb

Automatically generated by Colab.


# **Introduction: Intelligent Topic Categorization**

In the era of information overload, the ability to automatically and accurately categorize unstructured text is a fundamental pillar of Natural Language Processing (NLP). This project focuses on building a robust classification model capable of distinguishing between **six diverse domains:**
 1. **Politics**
 2. **Health**
 3. **Emotion**
 4. **Financial**
 5. **Sport**
 6. **Science**.

 By moving from traditional frequency-based models to State-of-the-Art (SOTA) ***Transformers***, we explore how deep semantic understanding can solve complex linguistic tasks.



---
**The Challenge:**

Developing a classifier for this dataset is not just "identifying keywords". The real technical difficulty depend on the three core points:
1. **Class Imbalance:**

Using a dataset with class **imbalance**, where categories like **Politics** have roughly ten times more samples than **Science**, standard models naturally become biased. They tend to predict the majority class because it contributes most to the overall "global accuracy".



*   **The Obstacle:** Achieving a high **Macro-F1-Score** and good overall **accuracy** treats minority classes like Science and Sport with the same attention as the dominant Politics class.

*   **The Solution:** I implemented **Weighted Cross-Entropy Loss** and **Balanced Class Weights**. This forces the model to make attention when it misclassifies a minority sample.

2. **The "Context" Problem**:

In topic classification, different categories often share the same vocabulary. For example, a political speech about a hospital budget contains both "Political" and "Health" keywords.

*  **The Obstacle:** Traditional models like **Logistic Regression** (using TF-IDF) only see a **"Bag of Words"**. They struggle to distinguish the primary intent when two topics use similar language.

*  **The Solution:** I utilized a **BERT-base Transformer**. By using Self-Attention, the model reads the entire sentence structure to understand **context—distinguishing** between a "political"  and "health" context.

3. **The Preprocessing Step:**
I used standard NLP data cleaning:
*  Lemmatization
*  Stopwords
*  Checking null values
*  Word Tokenization
*  Vectorization
*  Handling imbalanced data


---

**Approach**

In order to build a high-performance classification model, I followed a two-stage experimental design:

1.  Data Preprocessing
2.  Statistical Baseline (Logical Regression)
3.  Deep Learning Architecture (BERT-base)

---

**Project Objective:**

The objective of the mini project is to demonstrate how **Deep learning architectures like BERT** can overcome the limitations of traditional statistical models by capturing **bidirectional** context and resolving class imbalances in complex, real-world text classification tasks.

---

Note:

*  **Dataset:** The model was training using the topic classification dataset from kaggle.

* **Source:** https://www.kaggle.com/datasets/baraamelhem/topic-classification-dataset/data?select=topic_classification_data.csv
*  **Classes:** 6 (Politics, Health ,Emotion ,Financial ,Sport ,Science.

**Install Dependencies**
"""

!pip install kagglehub

!pip install -q nltk scikit-learn matplotlib seaborn keras

!pip install --upgrade transformers datasets evaluate accelerate --quiet

"""**Importation**"""

import os, re, torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import string
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import evaluate
import kagglehub

import nltk
nltk.download('stopwords')
nltk.download('wordnet')

import nltk
nltk.download('punkt_tab')

"""**Download Dataset from Kaggle**"""

path = kagglehub.dataset_download("baraamelhem/topic-classification-dataset")
df = pd.read_csv(os.path.join(path, "topic_classification_data.csv"))

"""**Example of Dataset**"""

print("Example of dataset:")
df.head()

"""# **Exploratory Data Analysis**"""

df.shape

df.columns

#removing column 'Unnamed: 0' :
df.drop('Unnamed: 0', axis=1, inplace=True)

df.head()

df['label'].value_counts()

#Data Distribution
plt.figure(figsize=(10, 5))
sns.countplot(x='label', data=df, palette='viridis')
plt.title("Visual Evidence of Class Imbalance")
plt.show()

#removing the duplicated value:
df.drop_duplicates(inplace=True)
print(df.shape)

#Checking of null values and removing them using dropna()
print(df.isnull().sum())

df = df.dropna(subset=['content'])

print(df.isnull().sum())

"""# **Data Cleaning**

**Removing Punctuation**
"""

def remove_punctuation(text):
  punctuationfree = "".join([i for i in text if i not in string.punctuation])
  return punctuationfree

df['content'] = df['content'].apply(lambda x:remove_punctuation(x))
df.head()

"""**Making words to lower letters**"""

df['content'] = df['content'].apply(lambda x: x.lower())
df.head()

"""**Tokenization: each sentence is split into words**"""

df['content'] = df['content'].apply(word_tokenize)
df.head()

"""**Stopwords using NLTK Library**"""

stopwords = nltk.corpus.stopwords.words('english')
def remove_stopwords(text):
  output=[i for i in text if i not in stopwords]
  return output

df['content'] = df['content'].apply(lambda x:remove_stopwords(x))
df.head()

"""**Lemmatization:** words are reduced to their base (dictionary) form to normalize different grammatical variations."""

lemmatizer = WordNetLemmatizer()
df['content'] = df['content'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

df.head()

"""**Joining Tokens:** after lemmatization, the tokens are joined back into a single sentence"""

def join_token(tokens):
  if isinstance(tokens, list):
    return ' '.join(tokens)
  return str(tokens)
df['content'] = df['content'].apply(join_token)
df.head()

"""## Handling Class Imbalance

Our dataset is heavily imbalanced:

| Class      | #Samples |
|-----------|-----------|
| Politics  | 37797     |
| Health    | 36952     |
| Emotion   | 28362     |
| Financial | 22981     |
| Sport     | 6077      |
| Science   | 4634      |

Minority classes (Sport, Science) could easily be ignored by the models if no adjustment is made.

**Approach in Logistic Regression (TF-IDF)**

- Using `class_weight='balanced'` in `LogisticRegression`.  
- This automatically assigns a **higher penalty to misclassifying minority class samples**, so the model make more attention to underrepresented topics.  


**Approach in BERT (Transformer)**

- BERT uses the standard **cross-entropy loss**.  
- I can optionally provide **per-class weights** to the loss function, computed as inverse frequency of each class.  
- This ensures that misclassifying minority topics contributes more to the loss, encouraging the model to learn them effectively.  

**This will help to:**

- Prevents bias toward majority classes (Politics, Health)  
- Improves F1-score and recall for rare classes (Sport, Science)  
- Demonstrates ethical and frugal handling of data imbalance
"""

# Original counts
class_counts = df['label'].value_counts()
classes = class_counts.index

# Compute class weights (inverse frequency)
total = class_counts.sum()
class_weights = total / (len(classes) * class_counts)
class_weights_list = class_weights.values

# Plot
plt.figure(figsize=(10,5))
bar_width = 0.35
x = np.arange(len(classes))
plt.bar(x - bar_width/2, class_counts.values, width=bar_width, label='Original Counts')
plt.bar(x + bar_width/2, class_weights_list*10000, width=bar_width, label='Effective Weight (scaled)')
plt.xticks(x, classes, rotation=45)
plt.ylabel('Counts / Effective Weight (scaled)')
plt.title('Class Imbalance and Weighting Effect')
plt.legend()
plt.show()

"""**Label Encoding:** converts categorical labels (text classes) into numerical values so that machine learning models can process them."""

le = LabelEncoder()
y_encoded = le.fit_transform(df['label'])

"""**Train–Validation Split:** the dataset is divided into training and validation sets."""

X_train, X_temp, y_train, y_temp = train_test_split(df['content'], y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)
print("Train:", X_train.shape[0], "Validation:", X_val.shape[0], "Test:", X_test.shape[0])

"""# **Model 1: Logistic Regression + TF-IDF**"""

#Initialize TF-IDF Vectorizer with max_features =10000 which limits the vocabulary to the 10 000 most import terms.
vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1,2))
X_train_vec = vectorizer.fit_transform(X_train)
X_val_vec = vectorizer.transform(X_val)
X_test_vec = vectorizer.transform(X_test)

# Logistic Regression: a linear classification model trained on TF-IDF features to predict article topics, using class_weight='balanced' to reduce bias toward majority classes and better handle dataset imbalance.
lr_model = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
lr_model.fit(X_train_vec, y_train)

# Predict
y_val_pred_lr = lr_model.predict(X_val_vec)

"""**Confusion Matrix**"""

# Metrics
print("Logistic Regression Metrics:")
print(classification_report(y_val, y_val_pred_lr, target_names=le.classes_))

# Confusion matrix
cm_lr = confusion_matrix(y_val, y_val_pred_lr)
plt.figure(figsize=(10,8))
sns.heatmap(cm_lr, annot=True, fmt="d", xticklabels=le.classes_, yticklabels=le.classes_, cmap='viridis')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Logistic Regression Confusion Matrix")
plt.show()

"""Before moving to **BERT** architecture, we must analyze the Logistic Regression fails. While the accuracy is 86%, the performance towards different categories presents many misclassification.

Error Analysis: Observed misclassification:
*  Financial predicted as emotion, health ..
*  Health predicted as Financial, science..

The most low error in our metrics is the **Science** category:
*  Recall: 0.76
*  Precision: 0.36 which is very low.

When the model predicts "Science" , it is actually wrong 64% of the time.

**Confusion Matrix:**
By looking at the Confusion Matrix, we can see exactly where these "False Positives" for Science are coming from:

*  257 Health articles were misclassified as Science.

*  115 Politics articles were misclassified as Science.

*  109 Emotion articles were misclassified as Science.

**Reson of this result:**
*  Health vs. Science: Words like research, study, or data appear often in both categories. Because of this overlap, the model sometimes predicts Science instead of Health.

*  Politics vs. Science: Articles about topics like climate policy include many scientific terms. As a result, the model sometimes focuses on the technical vocabulary and misclassifies them as Science instead of Politics.

---
**Transition to BERT:**

This error analysis shows that simple keyword matching is not enough. To solve this problem, we use BERT, which understands the context of words in a sentence using self-attention and bidirectional context

# **Model 2: BERT**

Preparing Data for BERT:
*  Data conversion
*  Tokenization
*  Dataset Formatting
"""

# Prepare datasets for HuggingFace
train_dataset = Dataset.from_dict({'text': list(X_train), 'label': list(y_train)})
val_dataset = Dataset.from_dict({'text': list(X_val), 'label': list(y_val)})
test_dataset = Dataset.from_dict({'text': list(X_test), 'label': list(y_test)})

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize(batch):
    return tokenizer(batch['text'], padding=True, truncation=True, max_length=128)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset.set_format('torch', columns=['input_ids','attention_mask','label'])
val_dataset.set_format('torch', columns=['input_ids','attention_mask','label'])
test_dataset.set_format('torch', columns=['input_ids','attention_mask','label'])

"""**BERT Model Initialization and Training Setup**

*  Model Selection: we use BERT (bert-base-uncased) for sequence classification. The classification head is initialized automatically with num_labels equal to number of our topic in dataset.

*  Training arguments: the model is trained for 3 epochs with a batch size of 16 (training) and 32 (validation).


"""

# Model
num_labels = len(le.classes_)
bert_model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=num_labels)


# Fixed TrainingArguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    fp16=True,
    report_to="none"
)

# Metrics
metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels, average='macro')

# Trainer
trainer = Trainer(
    model=bert_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    compute_metrics=compute_metrics
)

"""**Train the model**"""

# Train
trainer.train()

"""**BERT Validation, Metrics and Error Analysis:**

1.  Predictions: The trained BERT model is used to predict the labels of the validation dataset.
2.  Performance Metrics:
*  A classification report which is important that shows precision, recall and F1 score for each topic(category).
*  A confusion Matrix visualizes where the model confuses one category with another.
*  Error Analysis: Misclassified samples are examined to understand why the model made mistakes.
"""

# 1. BERT Predictions

val_results = trainer.predict(val_dataset)
y_val_pred_bert = np.argmax(val_results.predictions, axis=-1)
y_val_true = val_results.label_ids

# 2. Comparison Metrics

print("--- BERT-base Performance Report ---")

print(classification_report(y_val_true, y_val_pred_bert, target_names=le.classes_))

# Confusion Matrix
cm_bert = confusion_matrix(y_val_true, y_val_pred_bert)
plt.figure(figsize=(10,8))
sns.heatmap(cm_bert, annot=True, fmt="d",
            xticklabels=le.classes_, yticklabels=le.classes_,
            cmap='viridis')
plt.xlabel("Predicted Topic")
plt.ylabel("Actual Topic")
plt.title("BERT-base Confusion Matrix")
plt.show()

# 3.Scientific Error Analysis

print("\nMisclassified Samples:")
misclassified_idx = np.where(y_val_true != y_val_pred_bert)[0]

# 5 examples of misclassified Samples:
for i in misclassified_idx[:5]:

    original_text = X_val.iloc[i]
    true_label = le.inverse_transform([y_val_true[i]])[0]
    pred_label = le.inverse_transform([y_val_pred_bert[i]])[0]

    print(f"TEXT: {original_text[:150]}...")
    print(f"ACTUAL: {true_label} | PREDICTED: {pred_label}")
    print("-" * 30)

with open('requirements.txt', 'w') as f:
    f.write('torch\n')
    f.write('torchvision\n')
    f.write('matplotlib\n')
    f.write('seaborn\n')
    f.write('Pillow\n')
    f.write('numpy\n')
    f.write('scikit-learn\n')

print("requirements.txt")

"""# **Comparative Error Analysis: Linear Regression vs. BERT**

By comparing Logistic Regression (LR) and BERT , we see a major improvement when moving from Linear Regression model to deep contextual understanding.

1. **Precision Revolution - Catogory: Science:**

*  **Linear Regression:** Precision = 0.36. The model often misclassified technical terms , producing many false positives from Health and Emotion.
* **BERT:** Precision = 0.80. By understanding the context, BERT can make a difference between a medical study (Health) and Science.

2. **Solving Confusion between Health and Science categories:**

*  **LR confusion:** 257 Health topics misclassified as Science.
*  **BERT Confusion:** Only 38 Health topics are misclassified as Science.
Because the Linear Regression relied on shared vocabulary while BERT captures sentence context as bidirectionnal model.

3. **Performance on Minority Classes:**

*  **Sport F1-score:** from 0.79 reaching 0.93 in BERT
*  **Science F1-score:** from 0.49 reaching 0.74 in BERT
Although class imbalance, Bert leverages transfer learning to extract more information from fewer samples, making minority classes reliably predictable.

**Project Conclusion:**
This project shows the evolution from frequency-based NLP to transformer-based models.
"""